/*
 * Copyright 2014 ImaginativeThinking
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <QtGui/QGuiApplication>
#include "qtquick2applicationviewer.h"
#include "MyCalculatorViewModel.h"
#include <QQmlContext>

int main(int argc, char *argv[])
{
    // Traditional Qt window complete with message loop
    QGuiApplication app(argc, argv);

    // The engin that will load the OpenGL Scene Graph generated by the QtQuick engin and our QML script.
    QtQuick2ApplicationViewer viewer;

    // Setting the viewers root context to be an instance of the MyCalculatorViewModel class and giving it
    // a referance label of 'myCalculatorViewModel'; this referance label is how we will referance this instance
    // in our QML script.
    viewer.rootContext()->setContextProperty(QStringLiteral("myCalculatorViewModel"), new MyCalculatorViewModel());

    // Telling the viewer which QML script to load.
    viewer.setMainQmlFile(QStringLiteral("qml/QtQuickSampleApp/main.qml"));
    viewer.showExpanded();

    return app.exec();
}
